[package]
name = "MyCim"
version = "0.1.0"
edition = "2021"
description = "My cim for `some purpose`"

[dependencies]
iced = { version = "0.13.1", features = ["system", "canvas", "tokio", "debug"] }
bytesize = "1.1"
